version: 2
updates:
  - package-ecosystem: "poetry"   # ou "pip" se não usares Poetry aqui
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "develop"
    open-pull-requests-limit: 10
    reviewers:
      - "diogoribeiro7"
    labels: ["dependencies", "python"]

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    target-branch: "develop"
    versioning-strategy: increase
    reviewers:
      - "diogoribeiro7"
    labels: ["dependencies", "github-actions"]
