# Pre-commit hooks for code quality and consistency
# See https://pre-commit.com for more information

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: check-json
      - id: check-added-large-files
        args: ["--maxkb=1000"]
      - id: check-merge-conflict
      - id: check-ast
      - id: debug-statements
      - id: mixed-line-ending

  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black

  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: ["--profile=black"]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.8
    hooks:
      - id: ruff
        args: ["--fix", "--exit-non-zero-on-fix"]
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.3.3
    hooks:
      - id: prettier
        additional_dependencies: ["prettier@3.3.3"]
        files: "\\.(md|yaml|yml|json|toml|css|scss|html)$"

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.9
    hooks:
      - id: bandit
        args: ["-r", "src", "-lll"]

  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.25.0
    hooks:
      - id: commitizen
        stages: [commit-msg]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.2
    hooks:
      - id: mypy
        additional_dependencies:
          - types-requests
          - types-redis
        args: ["--strict", "--ignore-missing-imports"]
        files: ^src/

  - repo: local
    hooks:
      - id: pytest-check
        name: Run pytest with minimal config
        entry: poetry run pytest
        language: system
        pass_filenames: false
        always_run: true
        args: ["--maxfail=1", "--disable-warnings", "-q"]
        stages: [commit]
      - id: safety-check
        name: Safety dependency audit
        entry: bash
        language: system
        pass_filenames: false
        stages: [commit]
        args:
          - -c
          - >
            poetry export --format=requirements.txt --without-hashes
            --output /tmp/requirements.txt &&
            poetry run safety check --full-report --requirements /tmp/requirements.txt
