name: Scheduled Security Scan

on:
  schedule:
    - cron: "0 3 * * 1"
  workflow_dispatch:

jobs:
  security-audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.7.1
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Install dependencies
        run: |
          poetry install --no-interaction
          poetry export --format=requirements.txt --without-hashes --output /tmp/requirements.txt

      - name: Safety vulnerability scan
        run: poetry run safety check --full-report --requirements /tmp/requirements.txt

      - name: Bandit application scan
        run: poetry run bandit -r src/shap_analytics -lll
