name: Create issues from TODOs (Python)

on:
  workflow_dispatch:
    inputs:
      importAll:
        description: Import ALL TODOs from the checked-out ref (use with care)
        type: boolean
        required: false
        default: false
  schedule:
    - cron: "17 6 * * 1"  # Mondays 06:17 UTC — dry-run only
  push:
    branches: [ develop ]
    paths:
      - '**/*.py'
      - '**/*.pyi'
      - '**/*.pyx'
      - '**/*.pxd'
      - '**/*.ipynb'
      - 'pyproject.toml'
      - 'setup.cfg'
      - 'setup.py'
      - '!**/*.md'
      - '!.github/**'
  pull_request:
    branches: [ main ]
    paths:
      - '**/*.py'
      - '**/*.ipynb'
      - 'pyproject.toml'
      - 'setup.cfg'
      - 'setup.py'

permissions:
  contents: read
  issues: write
  pull-requests: read

concurrency:
  group: todo-issue-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # Dry-run scanning for PRs and schedule (no issues created)
  scan-dry-run:
    name: TODO scan (dry-run)
    runs-on: ubuntu-latest
    if: >
      (github.event_name == 'pull_request' || github.event_name == 'schedule') &&
      github.actor != 'dependabot[bot]' &&
      github.actor != 'github-actions[bot]'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Grep TODO-like tokens
        run: |
          set -euo pipefail
          grep -RInE --line-number --binary-files=without-match \
            --exclude-dir={.git,.github,.venv,venv,env,__pycache__,.pytest_cache,.mypy_cache,.ruff_cache,.nox,.tox,build,dist,site,htmlcov,coverage,node_modules,docs/_build} \
            -E '(^|\s)(TODO|FIXME|BUG|HACK|NOTE)\b' \
            . | tee todo_matches.txt || true
          echo "### TODO scan (dry-run)" >> $GITHUB_STEP_SUMMARY
          if [ -s todo_matches.txt ]; then
            echo "$(wc -l < todo_matches.txt) matches found." >> $GITHUB_STEP_SUMMARY
            echo "\n\`\`\`\n$(head -n 50 todo_matches.txt)\n\`\`\`\n" >> $GITHUB_STEP_SUMMARY
          else
            echo "No matches." >> $GITHUB_STEP_SUMMARY
          fi

      - name: Upload scan artifact
        uses: actions/upload-artifact@v5
        with:
          name: todo-scan
          path: todo_matches.txt
          if-no-files-found: ignore

  # Actual issue creation — ONLY on push or manual with importAll=true
  todos:
    name: Convert TODOs to issues
    runs-on: ubuntu-latest
    needs: []
    timeout-minutes: 10
    if: >
      !github.event.repository.fork &&
      github.actor != 'dependabot[bot]' &&
      github.actor != 'github-actions[bot]' &&
      (
        github.event_name == 'push' ||
        (github.event_name == 'workflow_dispatch' && inputs.importAll == true)
      )
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Run Issue Bot
        uses: juulsn/todo-issue@v1.1.4
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          excludePattern: >-
            ^(
              (\.git/|\.github/)|            # VCS/CI
              (\.venv/|venv/|env/)|          # venvs
              (__pycache__/)|                # py caches
              (\.pytest_cache/)|             # pytest cache
              (\.mypy_cache/)|               # mypy cache
              (\.ruff_cache/)|               # ruff cache
              (\.nox/|\.tox/)|               # nox/tox
              (build/|dist/|site/|htmlcov/|coverage/)|  # builds & reports
              (\.eggs/|\.idea/|\.vscode/)|   # tooling
              (node_modules/)|               # just in case
              (docs/_build/)                 # sphinx build
            )
          keywords: "TODO,FIXME,BUG,HACK,NOTE"
          bodyKeywords: "ASSIGNEE:|LABELS:|PRIORITY:"
          label: "todo"
          autoAssign: false
          caseSensitive: false
          titleSimilarity: 0.7     # dedupe sensitivity (0..1)
          reopenClosed: false

      - name: Summary
        run: |
          echo "### TODO issue creation" >> $GITHUB_STEP_SUMMARY
          echo "Scan completed. See Issues for newly created/updated items." >> $GITHUB_STEP_SUMMARY
